- pytest_watch/watcher.py
in case of `<directory>` is `None`, an error raises, as far as I tested
> Fix error when no <directory> arg

- pytest_watch/command.py
- pytest_watch/watcher.py
This add the default polling observer if `--poll` is given to the command.  Something worth noting, is that even for one of my smallest projects there is a bit of a lag in startup time before it starts getting file changes, so when testing I had to wait a few seconds after the first test ran before it would register file changes. After that lag, it worked pretty well.
Closes #9
> Add polling options for remote file systems

- pytest_watch/command.py
- pytest_watch/spooler.py
- pytest_watch/watcher.py
I believe this PR closes all outstanding issues (#5, #6, #7 and #8). If merged in, this probably calls for a version bump.
The README will probably need to be updated as well..
Options added / things modified:
- All positional arguments after `--` are now passed as is to `py.test` executable.
- Added support for multiple watched folders (passed as positional arguments).
- Allow to ignore sub folders (currently via an exact match only at a first level of each watched folder, but this could be improved quite easily to support arbitrary patterns). Note that this is done at the observer level and not in the event handler because if you have tens of thousands of files in a subfolder like `.tox` for example, the handler would get completely swamped by that (so a simple pattern matching inside …
> Multiple directories support, norecursedirs, passing args to pytest

- pytest_watch/watcher.py
Use shell=True only for MS Windows when executing py.test.
Ref: https://github.com/aldanor/pytest-watch/commit/dc066e212#commitcomment-11887976
> Fix passing args to py.test on POSIX systems

- pytest_watch/watcher.py
Using "white" explicitly causes problems on terminals with a light
background (e.g. Solarized White): just use the default fg.
I've not changed STYLE_HIGHLIGHT, but there `Fore.RESET + Style.BRIGHT`
might be better, too.
> Use the default fg for STYLE_NORMAL

- pytest_watch/command.py
- pytest_watch/watcher.py
This is meant to run a custom command before `py.test` is being called.
This can be useful to temporarily inject something like `dropdb
test_db`.
Fixes https://github.com/joeyespo/pytest-watch/issues/24.
> Add `--before-run` argument

- pytest_watch/watcher.py
In Python 3.5.0, subprocess.mswindows is renamed to subprocess._mswindows.
Fixes the following error:
```
Traceback (most recent call last):
File "/Users/coltonprovias/Development/MyNewLeaf/bin/ptw", line 11, in <module>
sys.exit(main())
File "/Users/coltonprovias/Development/MyNewLeaf/lib/python3.5/site-packages/pytest_watch/command.py", line 74, in main
quiet=args['--quiet'])
File "/Users/coltonprovias/Development/MyNewLeaf/lib/python3.5/site-packages/pytest_watch/watcher.py", line 130, in watch
event_handler.run()
File "/Users/coltonprovias/Development/MyNewLeaf/lib/python3.5/site-packages/pytest_watch/watcher.py", line 95, in run
shell=subprocess.mswindows)
AttributeError: module 'subprocess' has no attribute 'mswindows'
```
> Python 3.5.0 compatibility

- pytest_watch/command.py
- pytest_watch/watcher.py
This is useful in a Makefile, where Ctrl-C will not execute later
commands, and you want to restore settings from onfail, onpass etc.
> Add --onexit option

- pytest_watch/watcher.py
It works when using it through `--onfail 'python -c "print(\"\a\",
end=\"\")";'`, but not with the default options (without `--nobeep`).
I am not sure why that is required?!
I am using Python 3.5.0.
> Fix beep: flush the output buffer

- pytest_watch/command.py
- pytest_watch/ini_config_helpers.py
Things Added:
1. CollectIniPathPlugin which acts as a pytest plugin and does a dry-run of pytest to capture the ini path in CollectorIniPath.pytest_ini_path class variable
2. Load "pytest-watch" section from that ini and read the options
3. Mix that option with cmdline args, giving preference to cmdline values
Todo:
1. Add proper tests for ini args loading
2. <strike> Refactor string and boolean variable loading code to diff. func, whole thing looks bad now </strike>
> Added loading options from pytest.ini

- pytest_watch/watcher.py
py.test returns exit code 5 in case no tests are run/collected.
This can happen with tools like pytest-testmon.
Ref: https://github.com/pytest-dev/pytest/issues/812
Ref: https://github.com/tarpas/pytest-testmon/issues/31
> Handle exit code 5 as pass with py.test

- pytest_watch/command.py
- pytest_watch/watcher.py
This gets run on KeyboardInterrupt/SIGINT, which could be sent by a
`--beforerun` script, which kills all child processes (i.e. any
currently running py.test instance).
This also introduces the explicit "failed" state, which is not "not
passed" with py.test.
> Add --onsigint handler, run on KeyboardInterrupt

- pytest_watch/config.py
Seems inifile attribute was not always there.
Used with pytest 2.6.4 in another project resulted to fail at changed line.
> Fixed missing config.inifile attribute issue

- pytest_watch/watcher.py
This allows to re-run tests in case of changed files during the first
run already.
> Start observer before first run

- pytest_watch/config.py
This might happen for e.g. `ptw -- --vv`, where `--vv` is an invalid
option for `py.test`.
```
[0]   …/pyenv/project/bin/ptw(9)<module>()
-> load_entry_point('pytest-watch', 'console_scripts', 'ptw')()
[1]   …/pytest-watch/pytest_watch/command.py(85)main()
-> if not merge_config(args, pytest_args, verbose=args['--verbose']):
[2]   …/pytest-watch/pytest_watch/config.py(86)merge_config()
-> config_path = _collect_config(pytest_args, silent)
[3]   …/pytest-watch/pytest_watch/config.py(68)_collect_config()
-> return _run_pytest_collect(pytest_args)
[4]   …/pytest-watch/pytest_watch/config.py(52)_run_pytest_collect()
-> exit_code = pytest.main(argv, plugins=[collect_config_plugin])
…
[20]   …/pyenv/project/lib/python3.5/site-packages/_pytest/config.py(726)parse_args()
-> …
```
> Handle SystemExit also when calling _run_pytest_collect

- pytest_watch/watcher.py
I added the capability to show the current timestamp before running py.test
This is useful to find out when the tests are run when looking at the console output
> watcher.py: Show timestamp before running py.test

- AUTHORS.md
- CHANGES.md
- pytest_watch/watcher.py
My primary use case here is `pipenv`. I would like to be able to do:
```
$ pipenv run ptw
```
But this attempts to find a globally installed pytest:
> Running: py.test
> Error: [Errno 2] No such file or directory: 'py.test'
With this change, pytest-watch will call pytest as a module if not currently running in an activated virtual environment. This should also make running pytest-watch globally a nicer experience by ensuring the same Python interpreter is used to run both `ptw` and `py.test` even if the user's shell is misconfigured.
> Use the same interpreter when ptw is called outside of a virtual env

- pytest_watch/command.py
- pytest_watch/watcher.py
Maybe the documentation (i.e. https://github.com/joeyespo/pytest-watch/blob/ff2740e0ad5fb3018423c7440d13cb91f5045ae2/pytest_watch/command.py#L8) should also be changed to reflect the fact not only directories can be watched...
> Add watch single file feature

- pytest_watch/config.py
Handle config collection when no pytest inifile is present, finish config
collection via StopCollect even if an ini file is not present in the
cmdline_main configuration hook.
Resolves issues where `ptw` fails silently if errors are present in the
source module and an `pytest.ini` file is not present. See #85 #73
> Handle configuration/collection errors when no pytest inifile is present.

- MANIFEST.in
- README.rst
- create-readme-rst.sh
- setup.cfg
- setup.py
In reference to #81 , it was added README.rst file format for better presentation support into https://pypi.python.org and https://pypi.org repositories.
It was generated manually by command line.
A generator bash script was added to root of the project. If it is possible to add automated support for this during build time, it would be great.
For comparison purposes, I published two versions under test repositories to compare results:
Markdown format:
https://test.pypi.org/project/apast-pytest-watch/4.1.0.dev0/
Restructured format:
https://test.pypi.org/project/apast-pytest-watch/4.1.0.dev2/
It seems really better. Please, send me feedback in how I can improve this generation script.
[]'s,
Andre Pastore
> Added README.rst file format
